git-select-email: support user.selectableEmail

diff --git a/devel/git/git-select-email b/devel/git/git-select-email
--- a/devel/git/git-select-email
+++ b/devel/git/git-select-email
@@ -1,15 +1,26 @@
 #!/bin/sh
 # Quick way to select your user.email if you have multiple of them.
+# The emails are chosen from your GPG key and from user.selectableEmail.
 # Requires dialog(1).
 
 set -e
 GNUPGBIN="${GNUPGBIN:-gpg}"
 
-signingkey="$(git config user.signingkey)"
-test -n "$signingkey" || { echo >&2 "abort: no git config for user.signingkey"; exit 1; }
+get_emails() {
+	local signingkey="$(git config user.signingkey)"
+	if test -n "$signingkey"; then
+		$GNUPGBIN --with-colons -k "$signingkey" | grep uid:u | cut -d: -f10 | sed -nre 's/.*<(.*)>.*/\1/gp'
+	fi
+	git config --get-all user.selectableEmail
+}
 
-emails="$($GNUPGBIN --with-colons -k "$signingkey" | grep uid:u | cut -d: -f10 | sed -re 's/.*<(.*)>.*/\1 \1/g')"
-test -n "$signingkey" || { echo >&2 "abort: no gpg emails for $signingkey"; exit 1; }
+emails="$(get_emails | sed -e 's/.*/\0 \0/g')"
+if test -z "$emails"; then
+	echo >&2 "abort: no emails detected; you need to either:"
+	echo >&2 "- set user.signingkey and we will use that GPG key's emails, or"
+	echo >&2 "- set user.selectableEmail one or more times"
+	exit 1
+fi
 
 exec 3>&1; email="$(dialog --output-fd 4 --no-tags \
 --title "Select a value for user.email" --default-item "$(git config user.email)" \
