multisum: set exit codes properly

diff --git a/process/multisum b/process/multisum
--- a/process/multisum
+++ b/process/multisum
@@ -7,9 +7,45 @@
 # MITM attack by the same attacker. i.e., more geographically diverse hosts =>
 # more security.
 #
+# Exit codes:
+# 1 checksum mismatch!
+# 2 error calculating checksums locally
+# 3 error retrieving with wget
+
+USAGE="Usage: $0 <REMOTE> [<HOST> ...]"
+
+# when multiple errors occur on multiple hosts, we return smallest one
+# i.e. smallest should be most important
+ERR_MISMATCH=1
+ERR_LOCAL_SUM=2
+ERR_WGET=3
+ERR_SYNTAX_CFG=253
+ERR_SYNTAX_CMD=254
+
+HEADER="# multisum: default-whitespace-hosts"
+abort() { X="$1"; shift; echo >&2 "$@"; exit $X; }
+info() { true; }
+
+while getopts f:vh o; do
+	case $o in
+	v )
+		info() { echo >&2 "$@"; }
+		NEWOPTS="$NEWOPTS -v"
+		;;
+	h|\? ) echo >&2 "$USAGE"; exit $ERR_SYNTAX_CMD;;
+	esac
+done
+shift `expr $OPTIND - 1`
 
 TARGET="$1"
+if [ -z "$TARGET" ]; then
+	abort $ERR_SYNTAX_CMD "need to specify a target"
+fi
+
 shift
+if [ -z "$1" ]; then
+	abort $ERR_SYNTAX_CMD "need to specify some remote hosts"
+fi
 
 sum() {
 	SUM=$("$@")
@@ -18,29 +54,34 @@ sum() {
 }
 
 DST=$(basename "$TARGET")
-wget "$TARGET" -O "$DST"
-sum md5sum "$DST"; MD5SUM="$SUM"
-sum sha1sum "$DST"; SHA1SUM="$SUM"
-sum sha256sum "$DST"; SHA256SUM="$SUM"
+wget -nv "$TARGET" -O "$DST" || exit $ERR_WGET
+sum md5sum "$DST"; MD5SUM="$SUM" || exit $ERR_LOCAL_SUM
+sum sha1sum "$DST"; SHA1SUM="$SUM" || exit $ERR_LOCAL_SUM
+sum sha256sum "$DST"; SHA256SUM="$SUM" || exit $ERR_LOCAL_SUM
 
-echo "now running on remote hosts."
-echo "errors will be explicitly reported; no news is good news."
+info "now running on remote hosts."
+info "errors will be explicitly reported; no news is good news."
 
+X=256
 for remote in "$@"; do
-ssh "$remote" sh <<EOF
+info ">> $remote: "
+ssh "$remote" sh <<EOF || { Y=$?; [ $Y -lt $X ] && X=$Y; }
 test_sum() {
 EXPECT="\$1"
 ACTUAL=\$("\$2" "\$3" | cut '-d ' -f1)
 if [ "\$EXPECT" != "\$ACTUAL" ]; then
-	echo "\$2 mismatch: \$EXPECT != \$ACTUAL"
+	echo >&2 "\$2 mismatch: \$EXPECT != \$ACTUAL"
+	return 1
 fi
+return 0
 }
 
 TEMP=\$(tempfile)
 trap 'rm -f '"\$TEMP" EXIT INT TERM KILL
-wget -nv "$TARGET" -O "\$TEMP"
-test_sum "$MD5SUM" md5sum "\$TEMP"
-test_sum "$SHA1SUM" sha1sum "\$TEMP"
-test_sum "$SHA256SUM" sha256sum "\$TEMP"
+wget -nv "$TARGET" -O "\$TEMP" || exit $ERR_WGET
+test_sum "$MD5SUM" md5sum "\$TEMP" || exit $ERR_MISMATCH
+test_sum "$SHA1SUM" sha1sum "\$TEMP" || exit $ERR_MISMATCH
+test_sum "$SHA256SUM" sha256sum "\$TEMP" || exit $ERR_MISMATCH
 EOF
 done
+exit $X
